AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketNameParameter:
    Type: String
    Description: S3 Bucket Name
    Default: nb-lab-12-2-codepipeline
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameParameter
    DeletionPolicy: Delete
